---
  - name: Examples of lineinfile
    hosts: test
    
    tasks:
      - name: "Example1: Validate if a String or line is present in the file"
        tags: example1
        lineinfile:
          path: /var/test1
          line: "LogLevel debug"
          state: present
          backup: yes
        check_mode: yes
        register: example1out
